CREATE TABLE GCG_6108_Mult_Bom(
 "BIRUNID" BIGINT,
 "PARENT" CHAR(20),
 "PART" CHAR(20),
 "QUANTITY" DOUBLE,
 "DESCRIPTION" CHAR(30),
 "DESCRIPTION_2" CHAR(30),
 "DESCRIPTION_3" CHAR(30),
 "SEQUENCE_BOM" CHAR(4),
 "LEVEL" INTEGER,
 "KEY_SEQ" INTEGER);

CREATE INDEX "GCG_0000_Mult_Bom" ON "GCG_6108_Mult_Bom"("BIRUNID");